### ISSUE TITLE
Including doorkeeper-grants_assertion gem causes NoMethodError undefined method `authenticate_admin!'

### ISSUE THREAD

**Issue by adammcnamara** [doorkeeper-gem/doorkeeper-grants_assertion#6] opened 2014-11-08 18:52 UTC
Including this gem alongside doorkeeper causes: `NoMethodError at /oauth/applications undefined method 'authenticate_admin!' for #<Doorkeeper::ApplicationsController:0x007f8051ce0120>`

**Comment by NuckChorris** [comment] 2015-10-06 20:28
I'm not certain, but this seems (just from a quick compare of uniiverse/doorkeeper-grants_assertion against this) that this was likely fixed with 1b3acee3437fef80dd95038d40a1739aecdab0c0 — will try to confirm later

**Comment by vrybas** [comment] 2016-11-12 15:59
Just tried to access `/oauth/applications` in a browser with Doorkeeper '4.2.0' and 'master'(94b1e63) branch of this gem. Can't reproduce the issue.

@adammcnamara @gf3 @nathikazad @NuckChorris  can this one be closed?

**Comment by matfiz** [comment] 2016-11-12 16:04
I confirm, have just tried, no error have occurred. It seems to be fixed as @NuckChorris mentioned. I am closing this issue.

**Closed by matfiz** 2016-11-12 16:04 UTC
