### ISSUE TITLE
What are the params?

### ISSUE THREAD

**Issue by ebosantos** [doorkeeper-gem/doorkeeper-grants_assertion#20] opened 2016-04-28 23:00 UTC
I'm POSTing the following JSON to: /oauth/token

`{
"grant_type": "assertion",
"assertion": "social_provider_token"
}`

But I'm getting the following error message:

> ArgumentError (wrong number of arguments (given 1, expected 3)):
>   doorkeeper-grants_assertion (0.0.1) lib/doorkeeper/request/assertion.rb:10:in `initialize'

initializers/doorkeeper.rb

```
resource_owner_from_credentials do |routes|
    User.authenticate(params[:email], params[:password], request.remote_ip)
end
```

```
resource_owner_from_assertion do
    User.find(2)
end
```

```
grant_flows %w[assertion authorization_code password client_credentials]
```

Could you please help me?

**Comment by biske** [comment] 2016-07-14 08:02
+1

**Comment by matfiz** [comment] 2016-07-14 08:10
@ebosantos @biske Please remember you also do have to provide `client_id` and `client_secret`, so the complete set of params would be:
```coffeescript
$.post 'http://mapi.allforbody.pl/oauth2/token',
  client_id: d017e2ecd288d3141478af6667d9b7e1401e40b9c8e6290c52ad345bd7b99fe8
  client_secret: 67ac711924cc8c46cd4395c13cfe4af91eda7408dc27afbf0303492445b02ffc
  grant_type: assertion
  assertion: <access_token>```

**Comment by matfiz** [comment] 2016-07-14 09:39
@biske I agree it is not safe- then they are not confidential any more and such OAuth2 consumer is called *public client*. Ref. http://stackoverflow.com/a/36304034/1851563

**Comment by NuckChorris** [comment] 2016-07-16 05:57
This should probably not require client_secret — this only makes sense on server-side clients, and the "assertion" grant makes minimal sense in the context of a server-side client.

iirc (it's been a while since I read RFC 6749) public clients _should not_ have a secret

**Comment by piya23300** [comment] 2016-07-28 10:09
+1

**Comment by dsantosmerino** [comment] 2016-08-02 11:09
I'm getting also the same error. Could you provide a valid example?

**Comment by biske** [comment] 2016-08-02 14:36
@dsantosmerino, after adding client_id it works for me. Can you provide example app to reproduce issue?

**Comment by dsantosmerino** [comment] 2016-08-02 15:56
@biske I'm trying to get the token from Postman, and this is my body request: 
`{
    "client_id": "clientid",
    "client_secret": "secretid",
    "assertion": "32423444",
    "grant_type": "assertion"
}`

I've tried also providing de client info as get parameter, but I always get the same error than @ebosantos 

> ArgumentError (wrong number of arguments (given 1, expected 3)):
doorkeeper-grants_assertion (0.0.1) lib/doorkeeper/request/assertion.rb:10:in `initialize'

**Comment by dsantosmerino** [comment] 2016-08-05 12:06
@biske I've found the problem. I was using http://rubygems.org as source and there are some needed changes not updated in the gem.

**Comment by adityamajeti** [comment] 2016-09-02 09:22
I'm getting also the same error with cliend_id, client_secret, grant_type and assertion. How to resolve it?

**Comment by dsantosmerino** [comment] 2016-09-02 10:17
@adityamajeti I solved it just requiring the gem from this repo instead of rubygems.
`gem 'doorkeeper-grants_assertion', git: 'https://github.com/Badiapp/doorkeeper-grants_assertion'`

**Comment by adityamajeti** [comment] 2016-09-02 12:23
Thanks, dsantosmerino

After adding that gem file my   resource_owner_from_assertion  is executed but after identifying user  also  i'm not getting access_token getting 404 error somthing like

message:
  Document not found for class Doorkeeper::AccessToken with attributes {:application_id=>BSON::ObjectId('57c7131c2550c626d6eab983'), :resource_owner_id=>BSON::ObjectId('57c941fc2550c622e4d1f947'), :revoked_at=>nil}.
summary:
  When calling Doorkeeper::AccessToken.find_by with a hash of attributes, all attributes provided must match a document in the database or this error will be raised.
resolution:
  Search for attributes that are in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error.):

**Comment by matfiz** [comment] 2016-09-02 12:32
@adityamajeti Can you show us your `resource_owner_from_assertion`?

**Comment by adityamajeti** [comment] 2016-09-02 12:34
resource_owner_from_assertion do
    facebook = URI.parse('https://graph.facebook.com/me?access_token=' + params[:assertion])
    response = Net::HTTP.get_response(facebook)
    user_data = JSON.parse(response.body)
    # User.find_by_facebook_id(user_data['id'])
    User.find_by uid:user_data['id']    
  end

one more thing  in my application i want fb and eamil intregartion

**Comment by adityamajeti** [comment] 2016-09-03 05:04
@dsantosmerino,  In my app i'm using email and fb through doorkeeper  After adding this gem  gem 'doorkeeper-grants_assertion', git: 'https://github.com/Badiapp/doorkeeper-grants_assertion'   my normal access_token also not generating getting error

message:
Document not found for class Doorkeeper::AccessToken with attributes {:application_id=>BSON::ObjectId('57c7131c2550c626d6eab983'), :resource_owner_id=>BSON::ObjectId('57c941fc2550c622e4d1f947'), :revoked_at=>nil}.

**Comment by adityamajeti** [comment] 2016-09-03 14:55
HI, 
what is doorkeeper-grants assertion compatible version for doorkeeper = 4.0.0.rc1 and while using this GEM gem 'doorkeeper-grants_assertion', git: 'https://github.com/Badiapp/doorkeeper-grants_assertion  dependency issues are comming
 if i chage doorkeeper version to some other version access token is not generaing

**Comment by adityamajeti** [comment] 2016-09-05 06:42
@matfiz, I'm using doorkeeper 4.0.0.rc1 gem to generate access_token. but this   gem 'doorkeeper-grants_assertion', git: 'https://github.com/Badiapp/doorkeeper-grants_assertion' requires gem doorkeeper  4.0.0. while changing 4.0.0.   my doorkeeper logic is not working

**Comment by adityamajeti** [comment] 2016-09-05 18:49
@dsantosmerino, I'm using doorkeeper 4.0.0.rc1 gem to generate access_token. but this gem 'doorkeeper-grants_assertion', git: 'https://github.com/Badiapp/doorkeeper-grants_assertion' requires gem doorkeeper 4.0.0. while changing 4.0.0. my doorkeeper logic is not working  could you pl help me

**Comment by dsantosmerino** [comment] 2016-09-05 19:02
hey @adityamajeti, I didn't try it, but you can fork this repo and modify your required doorkeeper version.

**Comment by dsantosmerino** [comment] 2016-09-05 19:11
BTW, I would like to know how many people are actively using this gem. We need to take care about it and maintain the integration with doorkeeper main project. @tute do you have any suggestion or idea to improve this repo? We could start fixing the RubyGems' version.

**Comment by tute** [comment] 2016-09-05 19:40
Thanks for the text, @dsantosmerino. If you send over PRs improving the gem I will merge them, and then grant you access as maintainer if it's your will.

**Comment by moger777** [comment] 2017-05-26 15:05
@ebosantos @tute I think this is fixed on master. Maybe all we need is a 0.0.2 release.

**Comment by matfiz** [comment] 2018-01-16 14:01
This is fixed in the latest release, closing

**Closed by matfiz** 2018-01-16 14:01 UTC
